#!/usr/bin/env bash

# Запускайется после grunt build

ln -s dist www

cordova platforms add android
cordova platforms add ios

cordova plugin add org.apache.cordova.splashscreen
cordova plugin add org.apache.cordova.dialogs

./utils/prepare_res
