#!/usr/bin/env bash


# Sources:
#screen.png
#screen-hdpi-landscape.png
#screen-hdpi-portrait.png
#screen-ldpi-landscape.png
#screen-ldpi-portrait.png
#screen-mdpi-landscape.png
#screen-mdpi-portrait.png
#screen-xhdpi-landscape.png
#screen-xhdpi-portrait.png

src="./www/res/screens/android"
dst="./platforms/android/res"

cp -vr $src/screen.png $dst/drawable/screen.png
cp -vr $src/screen.png $dst/drawable-xhdpi/screen.png
cp -vr $src/screen.png $dst/drawable-hdpi/screen.png
cp -vr $src/screen.png $dst/drawable-ldpi/screen.png
cp -vr $src/screen.png $dst/drawable-mdpi/screen.png

src="./www/res/icons/android"
cp -vr $src/36.png $dst/drawable-ldpi/icon.png
cp -vr $src/48.png $dst/drawable-mdpi/icon.png
cp -vr $src/72.png $dst/drawable-hdpi/icon.png
cp -vr $src/96.png $dst/drawable-xhdpi/icon.png
cp -vr $src/96.png $dst/drawable/icon.png
