#!/usr/bin/env bash

# Запускайется после grunt build

cp -vr ./dist/ ./www/

cordova platforms add android
cordova platforms add ios

cordova plugin add org.apache.cordova.splashscreen

./utils/prepare_res
