#!/usr/bin/env bash
cordova -v

rm -f www
ln -s dist www

rm -fr platforms
mkdir ./platforms

rm -fr plugins
mkdir ./plugins

cordova platforms add android
cordova platforms add ios

#cordova plugin add org.apache.cordova.splashscreen
cordova plugin add org.apache.cordova.dialogs
